### PR TITLE
Fix spelling error in project 10

### PR DESCRIPTION
**Pull request by rowild**
Fix "architecutre" to "architecture".

### CODE REVIEW

**Comment by FilledStacks** [comment]
Nice! One thing is that the pubspec name has to be updated otherwise the application won't run given the fixed name package you're referencing doesn't exist.

**Comment by rowild** [comment]
Coming up!

**Comment by rowild** [comment]
Damn, you are quick! Was just looking how I could correct my "--append" (which should have been an "--amend")...
Thank you!
And thank you very much for all your tutorials!

**Comment by FilledStacks** [comment]
Thanks @rowild I appreciate the contribution. I guess the community is now lucky that you have that reading habit 😁

**Comment by rowild** [comment]
The weird thing about proof reader: they do NOT see their OWN errors!

**Pull request merged**
